"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.QueryDeclaration = exports.withScope = exports.Process = exports.renderProcess = undefined;
exports.injection = injection;

var _QueryDeclaration = require("./QueryDeclaration");

var _QueryDeclaration2 = _interopRequireDefault(_QueryDeclaration);

var _withScope = require("./withScope");

var _withScope2 = _interopRequireDefault(_withScope);

var _Process = require("./Process");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/**
 * Declares a GraphQL injection that will be automatically provided to the process scope on process initialization.
 *
 * The returned value is a query declaration object that is used to resolve the data from the initial process data
 * provided by the server.
 *
 * The server in turn uses JSON data generated by NPM module "babel-plugin-track-usage" to automatically determine
 * the injection queries.
 *
 */
function injection(query) {
  return new _QueryDeclaration2.default(query);
}

exports.renderProcess = _Process.renderProcess;
exports.Process = _Process.Process;
exports.withScope = _withScope2.default;
exports.QueryDeclaration = _QueryDeclaration2.default;
//# sourceMappingURL=index.js.map