"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = injection;

var _QueryDeclaration = require("./QueryDeclaration");

var _QueryDeclaration2 = _interopRequireDefault(_QueryDeclaration);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/**
 * Declares a GraphQL injection that will be automatically provided to the process scope on process initialization.
 *
 * The returned value is a query declaration object that is used to resolve the data from the initial process data
 * provided by the server.
 *
 * The server in turn uses JSON data generated by NPM module "babel-plugin-track-usage" to automatically determine
 * the injection queries.
 *
 * The GraphQL query value will be stripped of its first level. There can be only one query or mutation per injection.
 * This has no performance implications since all initial process queries are running at once on the server side anyway.
 *
 * @returns {QueryDeclaration} query declaration
 *
 */
function injection(query) {
  return new _QueryDeclaration2.default(query);
}
//# sourceMappingURL=injection.js.map