import QueryDeclaration from "./QueryDeclaration";
import withScope from "./withScope"
import { renderProcess, Process } from "./Process";

/**
 * Declares a GraphQL injection that will be automatically provided to the process scope on process initialization.
 *
 * The returned value is a query declaration object that is used to resolve the data from the initial process data
 * provided by the server.
 *
 * The server in turn uses JSON data generated by NPM module "babel-plugin-track-usage" to automatically determine
 * the injection queries.
 *
 */
export function injection(query)
{
    return new QueryDeclaration(query);
}

export { renderProcess, Process, withScope, QueryDeclaration }
